version: "2.3"

services:
  couchdb_1_7:
    image: couchdb:1.7.2
    environment:
      - "COUCHDB_USER=${COUCHDB_USER:-root}"
      - "COUCHDB_PASSWORD=${COUCHDB_PASSWORD:-a-secret}"
    restart: always
    ports:
      - "4895:5984"

  couchdb_2_3_1__1:
    image: couchdb:2.3.1
    command: -name couchdb@172.16.238.11 -setcookie thecookie
    environment:
      - "COUCHDB_USER=${COUCHDB_USER:-root}"
      - "COUCHDB_PASSWORD=${COUCHDB_PASSWORD:-a-secret}"
    restart: always
    networks:
      couchdb-cluster:
        ipv4_address: 172.16.238.11
    ports:
      - "15984:5984"

  couchdb_2_3_1__2:
    image: couchdb:2.3.1
    command: -name couchdb@172.16.238.12 -setcookie thecookie
    environment:
      - "COUCHDB_USER=${COUCHDB_USER:-root}"
      - "COUCHDB_PASSWORD=${COUCHDB_PASSWORD:-a-secret}"
    restart: always
    networks:
      couchdb-cluster:
        ipv4_address: 172.16.238.12
    ports:
      - "25984:5984"

  couchdb_2_3_1__3:
    image: couchdb:2.3.1
    command: -name couchdb@172.16.238.13 -setcookie thecookie
    environment:
      - "COUCHDB_USER=${COUCHDB_USER:-root}"
      - "COUCHDB_PASSWORD=${COUCHDB_PASSWORD:-a-secret}"
    restart: always
    networks:
      couchdb-cluster:
        ipv4_address: 172.16.238.13
    ports:
      - "35984:5984"

  couchdbstats1:
    image: "gesellix/couchdb-prometheus-exporter:${COUCHDB_EXPORTER_VERSION:-latest}"
    command: --couchdb.uri=http://couchdb_2_3_1__1:5984 --logtostderr
    environment:
      - "COUCHDB_USERNAME=${COUCHDB_USER:-root}"
      - "COUCHDB_PASSWORD=${COUCHDB_PASSWORD:-a-secret}"
    networks:
      couchdb-cluster:
        ipv4_address: 172.16.238.10
    ports:
      - "9984:9984"

  couchdbstats2:
    image: "gesellix/couchdb-prometheus-exporter:${COUCHDB_EXPORTER_VERSION:-latest}"
    command: --couchdb.uri=http://couchdb_2_3_1__2:5984 --logtostderr
    environment:
      - "COUCHDB_USERNAME=${COUCHDB_USER:-root}"
      - "COUCHDB_PASSWORD=${COUCHDB_PASSWORD:-a-secret}"
    networks:
      couchdb-cluster:
        ipv4_address: 172.16.238.20
    ports:
      - "9985:9984"

  cluster-setup:
    image: gesellix/couchdb-cluster-config:v16.1.0
    command: setup --delay 10s --timeout 30s --username ${COUCHDB_USER:-root} --password ${COUCHDB_PASSWORD:-a-secret} -nodes 172.16.238.11 -nodes 172.16.238.12 -nodes 172.16.238.13
    networks:
      couchdb-cluster:
        ipv4_address: 172.16.238.99

networks:
  couchdb-cluster:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
