version: "2.3"

services:
  couchdb0:
    image: apache/couchdb:1.7.1
    environment:
      - "COUCHDB_USER=${COUCHDB_USER:-root}"
      - "COUCHDB_PASSWORD=${COUCHDB_PASSWORD:-a-secret}"
    restart: always
    ports:
      - "4895:5984"

  couchdb1:
    image: apache/couchdb:2.1.1
    command: -name couchdb@172.16.238.11 -setcookie thecookie
    restart: always
    networks:
      couchdb-cluster:
        ipv4_address: 172.16.238.11
    ports:
      - "15984:5984"

  couchdb2:
    image: apache/couchdb:2.1.1
    command: -name couchdb@172.16.238.12 -setcookie thecookie
    restart: always
    networks:
      couchdb-cluster:
        ipv4_address: 172.16.238.12
    ports:
      - "25984:5984"

  couchdb3:
    image: apache/couchdb:2.1.1
    command: -name couchdb@172.16.238.13 -setcookie thecookie
    restart: always
    networks:
      couchdb-cluster:
        ipv4_address: 172.16.238.13
    ports:
      - "35984:5984"

  couchdbstats:
    image: "gesellix/couchdb-prometheus-exporter:${COUCHDB_EXPORTER_VERSION:-latest}"
    command: -couchdb.uri=http://couchdb1:5984 -logtostderr
    environment:
      - "COUCHDB.USERNAME=${COUCHDB_USER:-root}"
      - "COUCHDB.PASSWORD=${COUCHDB_PASSWORD:-a-secret}"
    networks:
      couchdb-cluster:
        ipv4_address: 172.16.238.10
    ports:
      - "9984:9984"

  cluster-setup:
    image: gesellix/couchdb-cluster-config:5
    command: -nodes 172.16.238.11 -nodes 172.16.238.12 -nodes 172.16.238.13
    networks:
      couchdb-cluster:
        ipv4_address: 172.16.238.99

networks:
  couchdb-cluster:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
