{
 "title": "CouchDB overview",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(couchdb_httpd_node_up, node_name)"
   },
   {
    "name": "database",
    "query": "label_values(couchdb_database_info,db_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Nodes",
   "type": "stat",
   "description": "Number of healthy nodes in the cluster.",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "couchdb_httpd_node_up" }
   ]
  },
  {
   "title": "Databases",
   "type": "stat",
   "description": "Number of databases in the cluster.",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "couchdb_httpd_databases_total" }
   ]
  },
  {
   "title": "Open shards",
   "type": "stat",
   "description": "Number of opened shards in the cluster.\n\nCouchDB only keeps opened shards that receive some activity: have received recent requests or are running a compaction job.",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "couchdb_httpd_open_databases{node_name=\"$node\"}"
    }
   ]
  },
  {
   "title": "Open OS files",
   "type": "stat",
   "description": "Number of opened file descriptors.\n\nCouchDB normally opens: two per db, one per view index, one for compaction files, and a couple more for other tasks such as logging.",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "couchdb_httpd_open_os_files{node_name=\"$node\"}"
    }
   ]
  },
  { "title": "HTTP server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (\n  label_replace(label_replace(rate(couchdb_httpd_status_codes{node_name=~\"$node\"}[$__rate_interval]),\n  \"status\", \"${1}xx\", \"code\", \"([0-9])..\"),\n  \"status\", \"${1}\", \"code\", \"([a-z]+)\"))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "couchdb_httpd_request_time{node_name=~\"$node\",metric=\"50\"}",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "couchdb_httpd_request_time{node_name=~\"$node\",metric=\"99\"}",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "couchdb_httpd_request_time{node_name=~\"$node\",metric=\"ArithmeticMean\"}",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "QPS by type",
   "type": "graph",
   "description": "Queries per second for special requests;\n- Bulk requests involve a single POST request but may produce a significant amount of changes to a db.\n- Temporary view reads are intended for development only (should aim to maintain at 0). They are forced to rebuild the view index in every request. Only in v1.X.X.\n- View reads hit a defined view in the db.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (node_name) (rate(couchdb_httpd_requests{node_name=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum by (node_name) (rate(couchdb_httpd_bulk_requests{node_name=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Bulk requests"
    },
    {
     "expr": "sum by (node_name) (rate(couchdb_httpd_temporary_view_reads{node_name=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "Temporary view reads"
    },
    {
     "expr": "sum by (node_name) (rate(couchdb_httpd_view_reads{node_name=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "View reads"
    }
   ]
  },
  {
   "title": "QPS by method",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (method) (rate(couchdb_httpd_request_methods{node_name=\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Continuous changes feeds listeners",
   "type": "graph",
   "description": "Feed listeners receive all changes to a database in the form of a stream of responses. Feed listeners may request only once but involve a significant portion of the database IO or load.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(couchdb_httpd_clients_requesting_changes{node_name=\"$node\"}[$__rate_interval])"
    }
   ]
  },
  {
   "title": "Auth cache - Hit/Miss",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(couchdb_httpd_auth_cache_hits{node_name=~\"$node\"}[$__rate_interval])",
     "legendFormat": "Hits"
    },
    {
     "expr": "rate(couchdb_httpd_auth_cache_misses{node_name=~\"$node\"}[$__rate_interval])",
     "legendFormat": "Misses"
    }
   ]
  },
  {
   "title": "Server IO - Writes/Reads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "-sum(rate(couchdb_httpd_database_reads{node_name=~\"$node\"}[$__interval]))",
     "legendFormat": "Reads"
    },
    {
     "expr": "sum(rate(couchdb_httpd_database_writes{node_name=~\"$node\"}[$__interval]))",
     "legendFormat": "Writes"
    }
   ]
  },
  { "title": "Database $database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 }, "repeat": "database" },
  {
   "title": "Documents",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (db_name) (couchdb_database_doc_count{node_name=~\"$node\",db_name=~\"$database\"})",
     "legendFormat": "{{db_name}}"
    }
   ]
  },
  {
   "title": "Size",
   "type": "graph",
   "description": "Data size represents the size of the data stored and Disk size the actual size on disk of the database. CouchDB runs periodic compaction jobs that will reduce the database disk size overhead.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (db_name) (couchdb_database_disk_size{node_name=~\"$node\",db_name=~\"$database\"})",
     "legendFormat": "Disk size"
    },
    {
     "expr": "sum by (db_name) (couchdb_database_data_size{node_name=~\"$node\",db_name=~\"$database\"})",
     "legendFormat": "Data size"
    },
    {
     "expr": "sum by (db_name) (couchdb_database_overhead{node_name=~\"$node\",db_name=~\"$database\"})",
     "legendFormat": "Overhead"
    }
   ]
  },
  { "title": "Database $database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Documents",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (db_name) (couchdb_database_doc_count{db_name=~\"$database\"})",
     "legendFormat": "{{db_name}}"
    }
   ]
  },
  {
   "title": "Size",
   "type": "graph",
   "description": "Data size represents the size of the data stored and Disk size the actual size on disk of the database. CouchDB runs periodic compaction jobs that will reduce the database disk size overhead.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (db_name) (couchdb_database_disk_size{db_name=~\"$database\"})",
     "legendFormat": "Disk size"
    },
    {
     "expr": "sum by (db_name) (couchdb_database_data_size{db_name=~\"$database\"})",
     "legendFormat": "Data size"
    },
    {
     "expr": "sum by (db_name) (couchdb_database_overhead{db_name=~\"$database\"})",
     "legendFormat": "Overhead"
    }
   ]
  },
  { "title": "Database $database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Documents",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (db_name) (couchdb_database_doc_count{db_name=~\"$database\"})",
     "legendFormat": "{{db_name}}"
    }
   ]
  },
  {
   "title": "Size",
   "type": "graph",
   "description": "Data size represents the size of the data stored and Disk size the actual size on disk of the database. CouchDB runs periodic compaction jobs that will reduce the database disk size overhead.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (db_name) (couchdb_database_disk_size{db_name=~\"$database\"})",
     "legendFormat": "Disk size"
    },
    {
     "expr": "sum by (db_name) (couchdb_database_data_size{db_name=~\"$database\"})",
     "legendFormat": "Data size"
    },
    {
     "expr": "sum by (db_name) (couchdb_database_overhead{db_name=~\"$database\"})",
     "legendFormat": "Overhead"
    }
   ]
  },
  { "title": "Database $database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Documents",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (db_name) (couchdb_database_doc_count{db_name=~\"$database\"})",
     "legendFormat": "{{db_name}}"
    }
   ]
  },
  {
   "title": "Size",
   "type": "graph",
   "description": "Data size represents the size of the data stored and Disk size the actual size on disk of the database. CouchDB runs periodic compaction jobs that will reduce the database disk size overhead.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum by (db_name) (couchdb_database_disk_size{db_name=~\"$database\"})",
     "legendFormat": "Disk size"
    },
    {
     "expr": "sum by (db_name) (couchdb_database_data_size{db_name=~\"$database\"})",
     "legendFormat": "Data size"
    },
    {
     "expr": "sum by (db_name) (couchdb_database_overhead{db_name=~\"$database\"})",
     "legendFormat": "Overhead"
    }
   ]
  }
 ]
}