---
name: Release
on:
  push:
    tags:
      - '*'
jobs:
  release:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
      - name: Checkout
        uses: actions/checkout@v2
#      - name: Unshallow
#        run: git fetch --prune --unshallow
#        working-directory: /home/runner/work/couchdb-prometheus-exporter/go/src/github.com/gesellix/couchdb-prometheus-exporter
      - name: Release binaries
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
...
